let f = _ => 42;
f("too", "many")

# output:
stdin:2:10
  ╷
2 │ f("too", "many")
  ╵          ^~~~~~
Error: Unexpected argument. The function takes 1 argument, but got 2.

stdin:1:11
  ╷
1 │ let f = _ => 42;
  ╵           ^~
Note: Function defined here.

stdin:2:2
  ╷
2 │ f("too", "many")
  ╵  ^
In call to function.
